export {default as Title} from './title'
export {default as Text} from './text'
export {default as Back} from './back'
export {default as Button} from './button'
export {default as Loader} from './loader'
export {default as Error} from './error'